
services:
  cart:
    image: ayshaat/cart:hw11
    build: .
    container_name: cart-service
    ports:
      - "8090:8090"
      - "9090:9090"
    environment:
      - ENV=production
    networks:
      - app-network
      - shared-net
    depends_on:
      cart-postgres:
        condition: service_healthy

  cart-postgres:
    image: postgres:16
    container_name: cart-db
    restart: always
    environment:
      POSTGRES_DB: cart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d cart" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - app-network
  

networks:
  app-network:
    external: true
    name: my-global-shared-network
  shared-net:
    external: true
    name: shared-net
