services:
  postgres:
    container_name: stock-db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lavender@30.06.04
      POSTGRES_DB: stocks
    ports:
      - "5433:5432" 
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  stocks:
    build: .
    container_name: stock-service
    environment:
      - ENV=production
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
