version: "3.8"

services:
  stocks:
    image: ayshaat/stocks:hw7
    container_name: stock-service
    ports:
      - "8081:8080"  
    env_file:
      - .env.docker
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: stock-db
    restart: always
    environment:
      POSTGRES_DB: stocks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lavender@30.06.04
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: my-global-shared-network
