version: "3.8"

services:
  stocks:
    image: ayshaat/stocks:hw11
    build: .
    container_name: stock-service
    depends_on:
      stock-postgres:
        condition: service_healthy
    ports:
      - "8081:8080"
      - "9094:9094"
    environment:
      - ENV=production
    networks:
      - app-network
      - shared-net

  stock-postgres:
    image: postgres:16
    container_name: stock-db
    restart: always
    environment:
      POSTGRES_DB: stocks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d stocks" ]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "5433:5432"
    networks:
      - app-network
      - shared-net


networks:
  app-network:
    external: true
    name: my-global-shared-network
  shared-net:
    external: true
    name: shared-net
