global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart:9000']

  - job_name: 'stocks-service'
    static_configs:
      - targets: ['stocks:9000']

  - job_name: 'metrics-consumer'
    static_configs:
      - targets: ['metrics-consumer:9095']
